import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Mono, Zilla_Slab } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const zilla_slab = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${zilla_slab.className} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
